### PR TITLE
Working on the playlist functionality

### PR DESCRIPTION
**Pull request by Benji377**
Playlists are the next thing we should focus on. They are present in almost every music player and I am sure we can get it to work in ours too.

### CODE REVIEW

**Comment by Benji377** [comment]
Hey @squivix, I will try to create the Playlistfragment as best as I can, but I have no idea how all those holders and stuff work so I might create a big mess. If you have time, could you please later take a look at it?

**Comment by Benji377** [comment]
This is how far I got for now. It's not much and I still need to test everything. Plus, this is just the overlay for the playlist, we still need something to be shown when one clicks on the playlist item.

**Comment by squivix** [comment]
Ok I'll focus on playlists next. Been trying to solve issue #125  for ages now. I even made a [sample app to isolate the issue](https://i.stack.imgur.com/RaZrM.gif)

**Comment by Benji377** [comment]
Hmm.. ok I will take a look, maybe I can help you out.

**Pull request merged**
