### PR TITLE
Adds a ViewPager in MainActivity to allow swiping between songs from the bottom info pane

### PR DESCRIPTION
**Pull request by squivix**

### CODE REVIEW

**Comment by squivix** [comment]
I'm working on doing the same thing with PlayerFragment. Do you think its a good a idea to let the user swipe between songs?

**Comment by Benji377** [comment]
I actually need to go to sleep now. I will merge this and take a look at it tomorrow and let you know.

**Comment by Benji377** [comment]
Ok, I looked at it and it's great! I just don't know how useful it is, but I really need to admit that swiping through songs like that is super satisfying hahaha. If you are able to implement it on the Playerfragment too sure.

**Comment by squivix** [comment]
> If you are able to implement it on the Playerfragment too sure.

Ok so an unfortunate side effect of the scrolling with a ViewPager is that the user can no longer see the song thumbnail rotation animation. Are you still ok with that? (In the future it will be replaced by the album art so I don't think we were gonna keep that anyway)

**Comment by Benji377** [comment]
Yeah, you are right. That's also probably what we should focus on next: Getting the songs data from the Media store. It's not a big side effect, as you said, it's just a matter of time and we would have needed to replace it anyway.

**Pull request merged**
