### PR TITLE
Implements playlists

### PR DESCRIPTION
**Pull request by squivix**
Finally done with the bare minimum of implementing playlists.

I still want to change a few things. For example PlaylistActivity should host another PlayerFragment to make sure the player is always available.

### CODE REVIEW

**Comment by squivix** [comment]
Playing from the PlaylistFragment is still unstable and sometimes crashes but like I said, I'm planning to rework it anyway so I'm not gonna fix it.

**Comment by Benji377** [comment]
Great! Well done!
I will look at it later, but for now I just wanted to show you how I intend to make the functionality to add playlists.
Here is a somewhat acceptáble drawing of how the fragment will look like:
Drawing

What I have in mind is to put a round button down in the right corner (in the image the red circle with the +). When you click on it a new popup like thing pops up in the middle of the fragment where you can specify details of the playlist. In this case the name and then save it.
We could use the same button to edit/remove playlist. For example when you click on the button we could make it so that a dropup menu opens with the options add, edit and delete.
Another option to remove playlist would be to like swipe them away and to edit them you long click on them. When deleting we would also need to ask if the user is sure to perform the action.

Tell me what you think about it and I will try to implement it later today if possible or tomorrow.

**Comment by squivix** [comment]
I think you're talking a fab (floating action button). Easy enough to implement. Right now I'm focused on reworking the interface a little to make player fragment hostable everywhere.

**Comment by Benji377** [comment]
> I think you're talking a fab (floating action button). Easy enough to implement. Right now I'm focused on reworking the interface a little to make player fragment hostable everywhere.

Yep exactly. It would also be great for helping in testing (at least for me) how the playlists get inserted in the db and if everything works smoothly.

**Pull request merged**
